[2022-02-25 22:11:59,875] [views.py:80] [views:get_context] [ERROR]- 身份错误
[2022-02-25 22:12:52,638] [views.py:86] [views:get_context] [INFO]- 执行更新：refs/heads/master：TEAM_JT/chile-cat-doc
[2022-02-25 22:12:53,521] [views.py:91] [views:get_context] [INFO]- 自动部署执行结果：
[2022-02-25 22:12:53,522] [views.py:93] [views:get_context] [INFO]- Fetching origin

[2022-02-25 22:12:53,522] [views.py:93] [views:get_context] [INFO]- HEAD is now at c910df3 测试提交

[2022-02-25 22:12:53,522] [views.py:93] [views:get_context] [INFO]- Already up-to-date.

[2022-02-25 22:25:12,408] [views.py:80] [views:get_context] [ERROR]- 身份错误
[2022-02-25 22:25:48,329] [views.py:80] [views:get_context] [ERROR]- 身份错误
